name: Build libmpv-android

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Symlink SDK
        working-directory: ./buildscripts
        run: |
          mkdir sdk
          ln -s ${ANDROID_HOME} ./sdk/android-sdk-linux
      - name: Bundle (default)
        working-directory: ./buildscripts
        run: |
          sudo chmod +x bundle_default.sh
          ./bundle_default.sh
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: |
            ./buildscripts/*.jar
            ./buildscripts/artifacts/**
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/main'
        with:
          draft: false
          prerelease: false
          tag_name: "v1.1.7-tls13"
          files: |
            buildscripts/artifacts/default/default-arm64-v8a.jar
            buildscripts/artifacts/default/default-armeabi-v7a.jar
            buildscripts/artifacts/default/default-x86_64.jar
            buildscripts/artifacts/default/default-x86.jar
